export const SET_UI = 'SET_UI';

export const LOAD_CURRENT_USER_REQUEST = 'LOAD_CURRENT_USER_REQUEST';
export const LOAD_CURRENT_USER_SUCCESS = 'LOAD_CURRENT_USER_SUCCESS';
export const LOAD_CURRENT_USER_FAILURE = 'LOAD_CURRENT_USER_FAILURE';

export const AUTH_USER_REQUEST = 'AUTH_USER_REQUEST';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';

export const LOAD_ROLES_REQUEST = 'LOAD_ROLES_REQUEST';
export const LOAD_ROLES_SUCCESS = 'LOAD_ROLES_SUCCESS';
export const LOAD_ROLES_FAILURE = 'LOAD_ROLES_FAILURE';

export const LOAD_RIGHTS_REQUEST = 'LOAD_RIGHTS_REQUEST';
export const LOAD_RIGHTS_SUCCESS = 'LOAD_RIGHTS_SUCCESS';
export const LOAD_RIGHTS_FAILURE = 'LOAD_RIGHTS_FAILURE';

export const ADD_ROLE_REQUEST = 'ADD_ROLE_REQUEST';
export const ADD_ROLE_SUCCESS = 'ADD_ROLE_SUCCESS';
export const ADD_ROLE_FAILURE = 'ADD_ROLE_FAILURE';

export const ASSIGN_ROLE_RIGHT_REQUEST = 'ASSIGN_ROLE_RIGHT_REQUEST';
export const ASSIGN_ROLE_RIGHT_SUCCESS = 'ASSIGN_ROLE_RIGHT_SUCCESS';
export const ASSIGN_ROLE_RIGHT_FAILURE = 'ASSIGN_ROLE_RIGHT_FAILURE';

export const REMOVE_ROLE_RIGHT_REQUEST = 'REMOVE_ROLE_RIGHT_REQUEST';
export const REMOVE_ROLE_RIGHT_SUCCESS = 'REMOVE_ROLE_RIGHT_SUCCESS';
export const REMOVE_ROLE_RIGHT_FAILURE = 'REMOVE_ROLE_RIGHT_FAILURE';

export const LOAD_TAGS_REQUEST = 'LOAD_TAGS_REQUEST';
export const LOAD_TAGS_SUCCESS = 'LOAD_TAGS_SUCCESS';
export const LOAD_TAGS_FAILURE = 'LOAD_TAGS_FAILURE';

export const ADD_TAG_REQUEST = 'ADD_TAG_REQUEST';
export const ADD_TAG_SUCCESS = 'ADD_TAG_SUCCESS';
export const ADD_TAG_FAILURE = 'ADD_TAG_FAILURE';

export const UPDATE_TAG_REQUEST = 'UPDATE_TAG_REQUEST';
export const UPDATE_TAG_SUCCESS = 'UPDATE_TAG_SUCCESS';
export const UPDATE_TAG_FAILURE = 'UPDATE_TAG_FAILURE';

export const DELETE_TAG_REQUEST = 'DELETE_TAG_REQUEST';
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';
export const DELETE_TAG_FAILURE = 'DELETE_TAG_FAILURE';

export const LOAD_ARTICLES_REQUEST = 'LOAD_ARTICLES_REQUEST';
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';
export const LOAD_ARTICLES_FAILURE = 'LOAD_ARTICLES_FAILURE';

export const UPDATE_ARTICLE_REQUEST = 'UPDATE_ARTICLE_REQUEST';
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS';
export const UPDATE_ARTICLE_FAILURE = 'UPDATE_ARTICLE_FAILURE';

export const ADD_ARTICLE_REQUEST = 'ADD_ARTICLE_REQUEST';
export const ADD_ARTICLE_SUCCESS = 'ADD_ARTICLE_SUCCESS';
export const ADD_ARTICLE_FAILURE = 'ADD_ARTICLE_FAILURE';

export const PUBLISH_ARTICLE_REQUEST = 'PUBLISH_ARTICLE_REQUEST';
export const PUBLISH_ARTICLE_SUCCESS = 'PUBLISH_ARTICLE_SUCCESS';
export const PUBLISH_ARTICLE_FAILURE = 'PUBLISH_ARTICLE_FAILURE';

export const UNPUBLISH_ARTICLE_REQUEST = 'UNPUBLISH_ARTICLE_REQUEST';
export const UNPUBLISH_ARTICLE_SUCCESS = 'UNPUBLISH_ARTICLE_SUCCESS';
export const UNPUBLISH_ARTICLE_FAILURE = 'UNPUBLISH_ARTICLE_FAILURE';